#!/bin/bash

# populate /web/html if empty

if [ ! -d /web/html ]; then
  mkdir /web/html
  chown -R apache.www-data /web/html
fi

if [ ! -d /web/html/ChurchCRM ]; then
  cd /tmp
  rm -R *
  # Latest Release Including RC
  curl -sOL "$(jq -r ".[0] | .assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases" ))"
  # Latest Full Release
  # curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"
  unzip -q *.zip
  cd churchcrm
  cp -Rp . /web/html
  cd ..
  rm -R *
  cp -f /web/churchcrm/Config.php /web/html/Include/Config.php
  chown -R apache.www-data /web/html
fi
