#!/bin/bash

# populate /web/html if empty

if [ ! -d /web/html ]; then
  mkdir /web/html
  chown -R apache.www-data /web/html
fi

if [ ! -d /web/html/ChurchCRM ]; then
  cd /tmp
  rm -R *
  # Latest Release Including RC
  curl -sOL "$(jq -r ".[0] | .assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases" ))"
  # Latest Full Release
  # curl -sOL "$(jq -r ".assets[] | .browser_download_url" < <( curl -s "https://api.github.com/repos/churchCRM/CRM/releases/latest" ))"
  unzip -q *.zip
  cd churchcrm
  cp -Rp . /web/html
  cd ..
  rm -R *
  # setting up auto logging for now
  cp -f /web/churchcrm/Config.php /web/html/Include/Config.php

  sed -i 's/||DB_SERVER_NAME||/crm-mariadb/g' /web/html/Include/Config.php
  sed -i 's/||DB_NAME||/'"$CRM_MARIADB_ENV_MARIADB_DATABASE"'/g' /web/html/Include/Config.php
  sed -i 's/||DB_USER||/'"$CRM_MARIADB_ENV_MARIADB_USER"'/g' /web/html/Include/Config.php
  sed -i 's/||DB_PASSWORD||/'"$CRM_MARIADB_ENV_MARIADB_PASSWORD"'/g' /web/html/Include/Config.php
  sed -i 's/||URL||//g' /web/html/Include/Config.php
  sed -i 's/||ROOT_PATH||//g' /web/html/Include/Config.php
  
  chown -R apache.www-data /web/html
fi
